### PR TITLE
Fix JSON schema generation

### PR DESCRIPTION
**Pull request by hluk**
Fix generating JSON schema (instead of less useful/common YAML schema).

Removes mentioning non-existing schema file. In future, there would be ideally a link to the schema file auto-generated by CI.

### CODE REVIEW

**Comment by amy2008** [comment]
@hluk I'm confused why we don't use the populate yaml file but the json file, is there any concern?

**Comment by hluk** [comment]
> I'm confused why we don't use the populate yaml file but the json file, is there any concern?

AFAIK, there are many tools that use JSON schema (not sure about YAML).

But would be OK with changing the format to YAML since the rule configuration are in YAML files and the schema would serve mainly as documentation (it is often easier to read YAML).

**Comment by amy2008** [comment]
> AFAIK, there are many tools that use JSON schema (not sure about YAML).
But lots of configurations are using YAML schema now,  especially the configuration in Konflux

**Comment by hluk** [comment]
> But lots of configurations are using YAML schema now,  especially the configuration in Konflux

Do you know any **tools** that check files using YAML schema? I'm actually not sure if "YAML schema" is even a thing.

**Comment by hluk** [comment]
I changed it so user can choose which format to generate: YAML or JSON

**Comment by mvalik** [comment]
maybe make a choice by the file extension?

**Comment by hluk** [comment]
> maybe make a choice by the file extension?

I thought about that, but that would complicate things in case user wants to output to stdout.

**Comment by amy2008** [comment]
> Do you know any **tools** that check files using YAML schema? I'm actually not sure if "YAML schema" is even a thing.

@hluk I will leave it to you, I just add a comment to say my concern why we need to do this change.
Feel free to ignore it if you think json is better, thanks.

**Comment by zhanglu1122** [comment]
> > But lots of configurations are using YAML schema now,  especially the configuration in Konflux
> 
> Do you know any **tools** that check files using YAML schema? I'm actually not sure if "YAML schema" is even a thing.

https://gitlab.cee.redhat.com/releng/konflux-release-data/-/tree/main/schemas/extra?ref_type=heads
https://gitlab.cee.redhat.com/releng/konflux-release-data/-/blob/main/tests/test_schemas.py?ref_type=heads

I see they using the above to do the yaml schema validation, if that's the thing you looking for

**Comment by hluk** [comment]
> > > But lots of configurations are using YAML schema now,  especially the configuration in Konflux
> > 
> > 
> > Do you know any **tools** that check files using YAML schema? I'm actually not sure if "YAML schema" is even a thing.
> 
> https://gitlab.cee.redhat.com/releng/konflux-release-data/-/tree/main/schemas/extra?ref_type=heads https://gitlab.cee.redhat.com/releng/konflux-release-data/-/blob/main/tests/test_schemas.py?ref_type=heads
> 
> I see they using the above to do the yaml schema validation, if that's the thing you looking for

Not sure if Konflux can help with this. We want users (or internal GitLab CI) to check their rule configuration using schema.

In the end, I think we will use the YAML schema (uploaded to the internal repo) only as a reference for the configuration. The rules will be checked with `retasc validate-rules` command (in the GitLab CI at least).

**Comment by zhanglu1122** [comment]
> > > > But lots of configurations are using YAML schema now,  especially the configuration in Konflux
> > > 
> > > 
> > > Do you know any **tools** that check files using YAML schema? I'm actually not sure if "YAML schema" is even a thing.
> > 
> > 
> > https://gitlab.cee.redhat.com/releng/konflux-release-data/-/tree/main/schemas/extra?ref_type=heads https://gitlab.cee.redhat.com/releng/konflux-release-data/-/blob/main/tests/test_schemas.py?ref_type=heads
> > I see they using the above to do the yaml schema validation, if that's the thing you looking for
> 
> Not sure if Konflux can help with this. We want users (or internal GitLab CI) to check their rule configuration using schema.
> 
> In the end, I think we will use the YAML schema (uploaded to the internal repo) only as a reference for the configuration. The rules will be checked with `retasc validate-rules` command (in the GitLab CI at least).

So the use case would be:
user define a rule yaml file, we want to ensure, the list field should contain list and some field can only contain certain values?

If this is the case, then I think it can be used. Take the releaseplanadmin schema validation as an example below:

The constraint is defined here - 
https://gitlab.cee.redhat.com/releng/konflux-release-data/-/blob/main/schemas/extra/releaseplanadmission.json?ref_type=heads#L21

Here is the actual field in user provided yaml - 
https://gitlab.cee.redhat.com/releng/konflux-release-data/-/blob/main/config/stone-prod-p02.hjvn.p1/product/ReleasePlanAdmission/osci-rhel-containers/rhel-10-0-beta-stage.yaml?ref_type=heads#L9

All the releaseplanadminsion yaml files will be tested in https://gitlab.cee.redhat.com/releng/konflux-release-data/-/blob/main/tests/test_schemas.py?ref_type=heads#L14

**Review by zhanglu1122 — APPROVED** [review]
LGTM

**Pull request merged**
