### PR TITLE
[Draft][Fix][KONFLUX] Enable releasing the app

### PR DESCRIPTION
**Pull request by amy2008**
JIRA: RHELWF-10985

### CODE REVIEW

**Comment by hluk** [comment]
I only skimmed the change, but there is huge amount of code for doing a seemingly simple operation - releasing/tagging a release container image for new change in main brach and passing required tests. I would prefer not to maintain this.

Can we schedule a meeting to discuss this?

**Comment by qgong** [comment]
@amy2008 @hluk @zhanglu1122 let's schedule a meeting to talk about the implment for this.

**Comment by amy2008** [comment]
@hluk @qgong @zhanglu1122 Yes, it's really a simple operation, but this week the konflux user support has the high priority, so I can make it simple next week, is that okay? @hluk

**Comment by xiangge** [comment]
Let's close as we meli already push images by the official pipeline, see the latest record on the project.

**Comment by amy2008** [comment]
Will reuse https://github.com/konflux-ci/release-service-catalog/tree/development/pipelines/push-to-external-registry

**Pull request closed without merging**
